# Generated by Django 6.1.1 on 2026-09-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
